apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "basalt.web-app.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: web-app
  {{- if or .Values.webApp.deploymentAnnotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.webApp.deploymentAnnotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.webApp.autoscaling.hpa.enabled }}
  replicas: {{ .Values.webApp.replicaCount }}
  {{- end }}
  {{- if .Values.webApp.updateStrategy }}
  strategy: {{- toYaml .Values.webApp.updateStrategy | nindent 4 }}
  {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" (dict "values" (list .Values.webApp.podLabels .Values.commonLabels) "context" .) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: web-app
  template:
    metadata:
      {{- if .Values.webApp.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.webApp.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: web-app
    spec:
      {{- include "basalt.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ template "basalt.web-app.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.webApp.automountServiceAccountToken }}
      {{- if .Values.webApp.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.webApp.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.webApp.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.webApp.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.webApp.podAffinityPreset "component" "web-app" "customLabels" $podLabels "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.webApp.podAntiAffinityPreset "component" "web-app" "customLabels" $podLabels "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.webApp.nodeAffinityPreset.type "key" .Values.webApp.nodeAffinityPreset.key "values" .Values.webApp.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.webApp.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.webApp.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.webApp.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.webApp.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.webApp.priorityClassName }}
      priorityClassName: {{ .Values.webApp.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.webApp.schedulerName }}
      schedulerName: {{ .Values.webApp.schedulerName | quote }}
      {{- end }}
      {{- if .Values.webApp.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.webApp.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.webApp.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.webApp.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.webApp.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.webApp.terminationGracePeriodSeconds }}
      {{- end }}
      initContainers:
        {{- if .Values.webApp.initContainers }}
          {{- include "common.tplvalues.render" (dict "value" .Values.webApp.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: nginx
          image: {{ template "basalt.web-app.image" . }}
          imagePullPolicy: {{ .Values.webApp.image.pullPolicy }}
          {{- if .Values.webApp.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.webApp.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.webApp.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.webApp.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.webApp.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.webApp.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: NODE_ENV
              value: production
            {{- if .Values.config.apiUrl }}
            - name: API_URL
              value: {{ .Values.config.apiUrl | quote }}
            {{- end }}
            {{- if .Values.webApp.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.webApp.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.webApp.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.webApp.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.webApp.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.webApp.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .Values.webApp.resources }}
          resources: {{- toYaml .Values.webApp.resources | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.webApp.containerPorts.http }}
            {{- if .Values.webApp.extraContainerPorts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.webApp.extraContainerPorts "context" $) | nindent 12 }}
            {{- end }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.webApp.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.webApp.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.webApp.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.webApp.livenessProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: http
          {{- end }}
          {{- if .Values.webApp.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.webApp.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.webApp.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.webApp.readinessProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: http
          {{- end }}
          {{- if .Values.webApp.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.webApp.customStartupProbe "context" $) | nindent 12 }}
          {{- else if .Values.webApp.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.webApp.startupProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: http
          {{- end }}
          {{- end }}
          {{- if .Values.webApp.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.webApp.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: empty-dir
              mountPath: /tmp
          {{- if .Values.webApp.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.webApp.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.webApp.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.webApp.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        - name: empty-dir
          emptyDir: {}