apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "basalt.otel-sqs-processor.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: otel-sqs-processor
  {{- if or .Values.otelSqsProcessor.deploymentAnnotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.otelSqsProcessor.deploymentAnnotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.otelSqsProcessor.autoscaling.hpa.enabled }}
  replicas: {{ .Values.otelSqsProcessor.replicaCount }}
  {{- end }}
  {{- if .Values.otelSqsProcessor.updateStrategy }}
  strategy: {{- toYaml .Values.otelSqsProcessor.updateStrategy | nindent 4 }}
  {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" (dict "values" (list .Values.otelSqsProcessor.podLabels .Values.commonLabels) "context" .) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: otel-sqs-processor
  template:
    metadata:
      {{- if .Values.otelSqsProcessor.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.otelSqsProcessor.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: otel-sqs-processor
    spec:
      {{- include "basalt.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ template "basalt.otel-sqs-processor.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.otelSqsProcessor.automountServiceAccountToken }}
      {{- if .Values.otelSqsProcessor.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.otelSqsProcessor.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.otelSqsProcessor.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.otelSqsProcessor.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.otelSqsProcessor.podAffinityPreset "component" "otel-sqs-processor" "customLabels" $podLabels "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.otelSqsProcessor.podAntiAffinityPreset "component" "otel-sqs-processor" "customLabels" $podLabels "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.otelSqsProcessor.nodeAffinityPreset.type "key" .Values.otelSqsProcessor.nodeAffinityPreset.key "values" .Values.otelSqsProcessor.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.otelSqsProcessor.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.otelSqsProcessor.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.otelSqsProcessor.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.otelSqsProcessor.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.otelSqsProcessor.priorityClassName }}
      priorityClassName: {{ .Values.otelSqsProcessor.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.otelSqsProcessor.schedulerName }}
      schedulerName: {{ .Values.otelSqsProcessor.schedulerName | quote }}
      {{- end }}
      {{- if .Values.otelSqsProcessor.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.otelSqsProcessor.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.otelSqsProcessor.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.otelSqsProcessor.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.otelSqsProcessor.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.otelSqsProcessor.terminationGracePeriodSeconds }}
      {{- end }}
      initContainers:
        {{- if .Values.otelSqsProcessor.initContainers }}
          {{- include "common.tplvalues.render" (dict "value" .Values.otelSqsProcessor.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: otel-sqs-processor
          image: {{ template "basalt.otel-sqs-processor.image" . }}
          imagePullPolicy: {{ .Values.otelSqsProcessor.image.pullPolicy }}
          {{- if .Values.otelSqsProcessor.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.otelSqsProcessor.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.otelSqsProcessor.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.otelSqsProcessor.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.otelSqsProcessor.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.otelSqsProcessor.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: PORT
              value: "3000"
            {{- if .Values.config.region }}
            - name: AWS_REGION
              value: {{ .Values.config.region | quote }}
            {{- end }}
            {{- if .Values.otelSqsProcessor.sqsQueueUrl }}
            - name: SQS_QUEUE_URL
              value: {{ .Values.otelSqsProcessor.sqsQueueUrl | quote }}
            {{- end }}
            {{- include "basalt.commonEnvVars" . | nindent 12 }}
            {{- if .Values.otelSqsProcessor.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.otelSqsProcessor.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.otelSqsProcessor.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.otelSqsProcessor.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.otelSqsProcessor.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.otelSqsProcessor.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .Values.otelSqsProcessor.resources }}
          resources: {{- toYaml .Values.otelSqsProcessor.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.otelSqsProcessor.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.otelSqsProcessor.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.otelSqsProcessor.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.otelSqsProcessor.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.otelSqsProcessor.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.otelSqsProcessor.sidecars "context" $) | nindent 8 }}
        {{- end }}
