{{- if and .Values.publicApi.metrics.enabled .Values.publicApi.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "basalt.public-api.fullname" . }}
  namespace: {{ default (include "common.names.namespace" .) .Values.publicApi.metrics.serviceMonitor.namespace | quote }}
  {{- $labels := include "common.tplvalues.merge" (dict "values" (list .Values.publicApi.metrics.serviceMonitor.labels .Values.commonLabels) "context" .) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: public-api
  {{- if or .Values.publicApi.metrics.serviceMonitor.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.publicApi.metrics.serviceMonitor.annotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  jobLabel: {{ .Values.publicApi.metrics.serviceMonitor.jobLabel | quote }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 6 }}
      {{- if .Values.publicApi.metrics.serviceMonitor.selector }}
      {{- include "common.tplvalues.render" (dict "value" .Values.publicApi.metrics.serviceMonitor.selector "context" $) | nindent 6 }}
      {{- end }}
  endpoints:
    - port: metrics
      path: "/metrics"
      {{- if .Values.publicApi.metrics.serviceMonitor.tlsConfig }}
      scheme: https
      tlsConfig: {{- include "common.tplvalues.render" ( dict "value" .Values.publicApi.metrics.serviceMonitor.tlsConfig "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.publicApi.metrics.serviceMonitor.interval }}
      interval: {{ .Values.publicApi.metrics.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.publicApi.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.publicApi.metrics.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.publicApi.metrics.serviceMonitor.honorLabels }}
      honorLabels: {{ .Values.publicApi.metrics.serviceMonitor.honorLabels }}
      {{- end }}
      {{- if .Values.publicApi.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{- include "common.tplvalues.render" ( dict "value" .Values.publicApi.metrics.serviceMonitor.metricRelabelings "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.publicApi.metrics.serviceMonitor.relabelings }}
      relabelings: {{- include "common.tplvalues.render" ( dict "value" .Values.publicApi.metrics.serviceMonitor.relabelings "context" $) | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
    - {{ include "common.names.namespace" . | quote }}
{{- end }}
