apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "basalt.otel-collector.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: otel-collector
  {{- if or .Values.otelCollector.deploymentAnnotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.otelCollector.deploymentAnnotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.otelCollector.autoscaling.hpa.enabled }}
  replicas: {{ .Values.otelCollector.replicaCount }}
  {{- end }}
  {{- if .Values.otelCollector.updateStrategy }}
  strategy: {{- toYaml .Values.otelCollector.updateStrategy | nindent 4 }}
  {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" (dict "values" (list .Values.otelCollector.podLabels .Values.commonLabels) "context" .) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: otel-collector
  template:
    metadata:
      {{- if .Values.otelCollector.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.otelCollector.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: otel-collector
    spec:
      {{- include "basalt.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ template "basalt.otel-collector.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.otelCollector.automountServiceAccountToken }}
      {{- if .Values.otelCollector.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.otelCollector.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.otelCollector.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.otelCollector.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.otelCollector.podAffinityPreset "component" "otel-collector" "customLabels" $podLabels "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.otelCollector.podAntiAffinityPreset "component" "otel-collector" "customLabels" $podLabels "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.otelCollector.nodeAffinityPreset.type "key" .Values.otelCollector.nodeAffinityPreset.key "values" .Values.otelCollector.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.otelCollector.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.otelCollector.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.otelCollector.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.otelCollector.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.otelCollector.priorityClassName }}
      priorityClassName: {{ .Values.otelCollector.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.otelCollector.schedulerName }}
      schedulerName: {{ .Values.otelCollector.schedulerName | quote }}
      {{- end }}
      {{- if .Values.otelCollector.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.otelCollector.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.otelCollector.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.otelCollector.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.otelCollector.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.otelCollector.terminationGracePeriodSeconds }}
      {{- end }}
      initContainers:
        {{- if .Values.otelCollector.initContainers }}
          {{- include "common.tplvalues.render" (dict "value" .Values.otelCollector.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: otel-collector
          image: {{ template "basalt.otel-collector.image" . }}
          imagePullPolicy: {{ .Values.otelCollector.image.pullPolicy }}
          {{- if .Values.otelCollector.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.otelCollector.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.otelCollector.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.otelCollector.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.otelCollector.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.otelCollector.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: AWS_OTEL_BUCKET_NAME
              value: {{ .Values.storage.otelBucket | quote }}
            {{- include "basalt.redisEnvVars" . | nindent 12 }}
            {{- if .Values.otelCollector.redisDb }}
            - name: REDIS_DB
              value: {{ .Values.otelCollector.redisDb | quote }}
            {{- end }}
            {{- if .Values.otelCollector.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.otelCollector.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.otelCollector.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.otelCollector.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.otelCollector.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.otelCollector.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .Values.otelCollector.resources }}
          resources: {{- toYaml .Values.otelCollector.resources | nindent 12 }}
          {{- end }}
          ports:
            - name: grpc
              containerPort: {{ .Values.otelCollector.containerPorts.grpc }}
            - name: http
              containerPort: {{ .Values.otelCollector.containerPorts.http }}
            - name: hc
              containerPort: {{ .Values.otelCollector.containerPorts.hc }}
            {{- if .Values.otelCollector.extraContainerPorts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.otelCollector.extraContainerPorts "context" $) | nindent 12 }}
            {{- end }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.otelCollector.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.otelCollector.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.otelCollector.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.otelCollector.livenessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: {{ .Values.otelCollector.containerPorts.hc }}
          {{- end }}
          {{- if .Values.otelCollector.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.otelCollector.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.otelCollector.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.otelCollector.readinessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: {{ .Values.otelCollector.containerPorts.hc }}
          {{- end }}
          {{- if .Values.otelCollector.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.otelCollector.customStartupProbe "context" $) | nindent 12 }}
          {{- else if .Values.otelCollector.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.otelCollector.startupProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: {{ .Values.otelCollector.containerPorts.hc }}
          {{- end }}
          {{- end }}
          {{- if .Values.otelCollector.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.otelCollector.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true
          {{- if .Values.otelCollector.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.otelCollector.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.otelCollector.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.otelCollector.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "basalt.otel-collector.fullname" . }}
      {{- if .Values.otelCollector.extraVolumes }}
      {{- include "common.tplvalues.render" (dict "value" .Values.otelCollector.extraVolumes "context" $) | nindent 8 }}
      {{- end }}
