apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "basalt.jobs-runner.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: jobs-runner
  {{- if or .Values.jobsRunner.deploymentAnnotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.jobsRunner.deploymentAnnotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.jobsRunner.autoscaling.hpa.enabled }}
  replicas: {{ .Values.jobsRunner.replicaCount }}
  {{- end }}
  {{- if .Values.jobsRunner.updateStrategy }}
  strategy: {{- toYaml .Values.jobsRunner.updateStrategy | nindent 4 }}
  {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" (dict "values" (list .Values.jobsRunner.podLabels .Values.commonLabels) "context" .) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: jobs-runner
  template:
    metadata:
      {{- if .Values.jobsRunner.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.jobsRunner.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: jobs-runner
    spec:
      {{- include "basalt.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ template "basalt.jobs-runner.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.jobsRunner.automountServiceAccountToken }}
      {{- if .Values.jobsRunner.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.jobsRunner.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.jobsRunner.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.jobsRunner.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.jobsRunner.podAffinityPreset "component" "jobs-runner" "customLabels" $podLabels "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.jobsRunner.podAntiAffinityPreset "component" "jobs-runner" "customLabels" $podLabels "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.jobsRunner.nodeAffinityPreset.type "key" .Values.jobsRunner.nodeAffinityPreset.key "values" .Values.jobsRunner.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.jobsRunner.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.jobsRunner.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.jobsRunner.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.jobsRunner.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.jobsRunner.priorityClassName }}
      priorityClassName: {{ .Values.jobsRunner.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.jobsRunner.schedulerName }}
      schedulerName: {{ .Values.jobsRunner.schedulerName | quote }}
      {{- end }}
      {{- if .Values.jobsRunner.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.jobsRunner.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.jobsRunner.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.jobsRunner.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.jobsRunner.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.jobsRunner.terminationGracePeriodSeconds }}
      {{- end }}
      initContainers:
        {{- if .Values.jobsRunner.initContainers }}
          {{- include "common.tplvalues.render" (dict "value" .Values.jobsRunner.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: jobs-runner
          image: {{ template "basalt.jobs-runner.image" . }}
          imagePullPolicy: {{ .Values.jobsRunner.image.pullPolicy }}
          {{- if .Values.jobsRunner.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.jobsRunner.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.jobsRunner.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.jobsRunner.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.jobsRunner.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.jobsRunner.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            {{- include "basalt.commonEnvVars" . | nindent 12 }}
            {{- if .Values.jobsRunner.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.jobsRunner.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.jobsRunner.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.jobsRunner.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.jobsRunner.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.jobsRunner.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .Values.jobsRunner.resources }}
          resources: {{- toYaml .Values.jobsRunner.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.jobsRunner.metrics.enabled }}
          ports:
            - name: metrics
              containerPort: {{ .Values.jobsRunner.containerPorts.metrics }}
          {{- end }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.jobsRunner.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.jobsRunner.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.jobsRunner.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.jobsRunner.livenessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: 3000
          {{- end }}
          {{- if .Values.jobsRunner.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.jobsRunner.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.jobsRunner.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.jobsRunner.readinessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: 3000
          {{- end }}
          {{- if .Values.jobsRunner.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.jobsRunner.customStartupProbe "context" $) | nindent 12 }}
          {{- else if .Values.jobsRunner.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.jobsRunner.startupProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: 3000
          {{- end }}
          {{- end }}
          {{- if .Values.jobsRunner.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.jobsRunner.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.jobsRunner.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.jobsRunner.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.jobsRunner.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.jobsRunner.sidecars "context" $) | nindent 8 }}
        {{- end }}